config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/index'
  root 'pages#index'

  resources :albums, only: %i[index show]
  resources :artists, only: %i[index show] do
    resource :image, only: %i[create]
  end
  resources :songs, only: %i[index]
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs

  validates :name, :path, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string
#  path       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ApplicationRecord
  has_many :albums
  has_one_attached :image

  validates :name, :path, presence: true
end

app/models/song.rb
# frozen_string_literal: true

class Song < ApplicationRecord
  belongs_to :album

  validates :name, :file_name, presence: true
end

app/controllers/albums_controller.rb
# frozen_string_literal: true

class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    @songs = @album.songs
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
    @albums = @artist.albums
  end
end

app/controllers/images_controller.rb
# frozen_string_literal: true

class ImagesController < ApplicationController
  def create
    artist = Artist.find(params[:artist_id])
    image = params[:image].present? ? params[:image] : nil
    artist.update(image: image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/songs_controller.rb
# frozen_string_literal: true

class SongsController < ApplicationController
  def index
    @songs = Song.includes(album: [:artist])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album.html.slim
.card
  .card-image
    figure.image.is-4by3
      img alt=("Placeholder image") src="https://bulma.io/images/placeholders/1280x960.png" /
  .card-content
    .media
      /.media-left
        figure.image.is-48x48
          img alt=("Placeholder image") src="https://bulma.io/images/placeholders/96x96.png" /
      .media-content
        p.title.is-6 = link_to album.name, album_path(album)
        p.subtitle.is-7 @johnsmith
    /.content
      | Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      | Phasellus nec iaculis mauris.
      a href="#" #css
      a href="#" #responsive
      br/
      time datetime="2016-1-1"  11:09 PM - 1 Jan 2016

app/views/albums/index.html.slim
.columns
  .column
    h1.title
      = @albums.size
      '
      | Albums
.columns
  .column
    - @albums.each_slice(4) do |slice|
      .columns
        - slice.each do |album|
          .column.is-one-quarter
            = render album

app/views/albums/show.html.slim
.columns.is-vcentered
  .column.is-narrow
    figure class="image is-128x128"
      img src="https://bulma.io/images/placeholders/128x128.png"
  .column
    h1.title = @album.name
    h4.subtitle
      | by 
      = @album.artist.name
    hr
.columns
  .column
    table.table.is-fullwidth
      thead
        tr
          th width=10 #
          th Name
      tbody
        - @songs.each_with_index do |song, index|
          tr
            td = index + 1
            td = song.name

app/views/artists/index.html.slim
.columns
  .column
    h1.title
      = @artists.size
      '
      | Artists
.columns
  .column
    - @artists.each_slice(4) do |slice|
      .columns
        - slice.each do |artist|
          .column.is-one-quarter
            .card
              .card-image
                figure.image.is-4by4
                  - if artist.image.present?
                    = image_tag artist.image.variant(combine_options: { resize: '320x320^', gravity: 'center', extent: '320x320' })
                  - else
                    img src="https://bulma.io/images/placeholders/480x480.png" /
              .card-content
                .media
                  .media-content
                    p.title.is-6 = link_to artist.name, artist_path(artist)
                    p.subtitle.is-7 @johnsmith

app/views/artists/show.html.slim
.columns.is-vcentered
  .column.is-narrow
    - if @artist.image.present?
      figure class="image"
        image-uploader image=url_for(@artist.image.variant(combine_options: { resize: '320x320^', gravity: 'center', extent: '320x320' }))  artist-id=@artist.id
    - else
      image-uploader artist-id=@artist.id
  .column
    h1.title = @artist.name
.columns
  .column
    hr
    h3.title.is-size-6 Albums
    - @albums.each_slice(4) do |slice|
      .columns
        - @albums.each do |album|
          .column.is-one-quarter
            = render album

app/views/layouts/_navbar.html.slim
nav.navbar aria-label=("main navigation") role="navigation" 
  .navbar-brand
    a.navbar-item href=root_url
      span.icon.is-medium
        i.fab.fa-itunes-note.fa-2x
    a.navbar-burger.burger aria-expanded="false" aria-label="menu" data-target="navbarBasicExample" role="button" 
      span aria-hidden="true" 
      span aria-hidden="true" 
      span aria-hidden="true" 
  #navbarBasicExample.navbar-menu
    .navbar-start
      / Search input
    .navbar-end
      .navbar-item
        .buttons
          a.button.is-link.is-light href="https://gitlab.com/hernanvicente/swp" target="_blank"
            span.icon.is-small
              i.fab.fa-gitlab
            span GitLab

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    title
      | Swp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    script crossorigin="anonymous" src="https://kit.fontawesome.com/fdbe6874d8.js"
  body
    = render 'layouts/navbar'
    section#vue-container
      .columns
        .column.is-2.sidebar-nav
          h1.title.is-size-5 Library
          ul
            li = link_to 'artists', artists_path, class: 'navbar-item'
            li = link_to 'albums', albums_path, class: 'navbar-item'
            li = link_to 'songs', songs_path, class: 'navbar-item'
        .column.main-content
          = yield

app/views/pages/index.html.slim
.columns
  .column.is-one-fifth
    h1.title.is-size-5 Recently played

app/views/songs/index.html.slim
.columns
  .column
    h1.title
      = @songs.size
      '
      | Songs
.columns
  .column
    table.table.is-fullwidth
      thead
        tr
          th width=10 #
          th Name
          th Artist
          th Album
      tbody
        - @songs.each_with_index do |song, index|
          tr
            td = index + 1
            td = song.name
            td = song.album.artist.name
            td = song.album.name